In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/processed/master_dataset.csv")

print(df.shape)
df.head()

(2693087, 12)

,session_id,timestamp,coolant_temp,map,rpm,speed,iat,maf,throttle_pos,ambient_temp,pedal_d,pedal_e
0,2017-07-05_Seat_Leon_RT_S_Stau,0.813,31.0,96.0,0.0,0.0,22.0,0.91,89.0,21.0,14.1,14.5
1,2017-07-05_Seat_Leon_RT_S_Stau,0.901,31.0,96.0,0.0,0.0,22.0,0.91,89.0,21.0,14.1,14.5
2,2017-07-05_Seat_Leon_RT_S_Stau,0.991,31.0,96.0,0.0,0.0,22.0,0.91,89.0,21.0,14.1,14.5
3,2017-07-05_Seat_Leon_RT_S_Stau,1.081,31.0,96.0,0.0,0.0,22.0,0.91,89.0,21.0,14.1,14.5
4,2017-07-05_Seat_Leon_RT_S_Stau,1.171,31.0,96.0,0.0,0.0,22.0,0.91,89.0,21.0,14.1,14.5

In [3]:
df["speed_delta"] = (
    df.groupby("session_id")["speed"]
      .diff()
)

df["rpm_delta"] = (
    df.groupby("session_id")["rpm"]
      .diff()
)

df["maf_delta"] = (
    df.groupby("session_id")["maf"]
      .diff()
)

df["map_delta"] = (
    df.groupby("session_id")["map"]
      .diff()
)

df["throttle_delta"] = (
    df.groupby("session_id")["throttle_pos"]
      .diff()
)

In [4]:
df[
    [
        "rpm",
        "speed",
        "maf",
        "map",
        "throttle_pos"
    ]
].describe()

                rpm         speed           maf           map  throttle_pos
count  2.693087e+06  2.693087e+06  2.693087e+06  2.693087e+06  2.693087e+06
mean   1.494851e+03  6.226178e+01  2.270533e+01  1.253437e+02  8.124717e+01
std    5.348602e+02  4.579184e+01  1.636204e+01  3.139688e+01  1.131043e+01
min    0.000000e+00  0.000000e+00  0.000000e+00  3.600000e+01  1.370000e+01
25%    1.109000e+03  1.900000e+01  1.163000e+01  1.040000e+02  8.350000e+01
50%    1.539000e+03  6.100000e+01  1.861000e+01  1.140000e+02  8.350000e+01
75%    1.851000e+03  1.020000e+02  2.913000e+01  1.370000e+02  8.350000e+01
max    4.315000e+03  2.180000e+02  1.292200e+02  2.470000e+02  8.900000e+01

In [5]:
df[
    [
        "rpm_delta",
        "speed_delta",
        "maf_delta",
        "map_delta",
        "throttle_delta"
    ]
].describe()

          rpm_delta   speed_delta     maf_delta     map_delta  throttle_delta
count  2.693006e+06  2.693006e+06  2.693006e+06  2.693006e+06    2.693006e+06
mean  -8.239863e-04 -3.639056e-05 -1.556402e-04 -1.428887e-03   -1.817746e-03
std    4.306749e+01  5.874300e-01  1.916238e+00  4.176113e+00    2.622654e+00
min   -2.703000e+03 -1.060000e+02 -7.867000e+01 -1.600000e+02   -6.980000e+01
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    0.000000e+00
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    0.000000e+00
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    0.000000e+00
max    1.866000e+03  4.300000e+01  9.155000e+01  1.350000e+02    7.530000e+01

In [6]:
df.nlargest(
    20,
    "rpm"
)[
    [
        "session_id",
        "timestamp",
        "rpm",
        "speed"
    ]
]

                                         session_id  timestamp     rpm  speed
1378964  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2697.709  4315.0   26.0
1378965  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2697.798  4315.0   39.0
1378966  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2697.888  4315.0   39.0
1378967  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2697.978  4315.0   39.0
1378968  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2698.068  4315.0   39.0
1378969  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2698.158  4315.0   39.0
1378970  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2698.249  4315.0   39.0
1378971  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2698.339  4315.0   39.0
1378972  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2698.429  4315.0   39.0
1378973  2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis   2698.519  4315.0   39.0
986787             2017-08-04_Seat_Leon_S_RT_Normal   2057.097  3788.0   56.0
986788             2017-08-04_Seat_Leon_S_RT_Normal   2057.159  3788.0   65.0
986789             2017-08-04_Seat_Leon_S_RT_Normal   2057.247  3788.0   65.0
986790             2017-08-04_Seat_Leon_S_RT_Normal   2057.309  3788.0   65.0
986791             2017-08-04_Seat_Leon_S_RT_Normal   2057.397  3788.0   65.0
986792             2017-08-04_Seat_Leon_S_RT_Normal   2057.458  3788.0   65.0
986793             2017-08-04_Seat_Leon_S_RT_Normal   2057.607  3788.0   65.0
986794             2017-08-04_Seat_Leon_S_RT_Normal   2057.697  3788.0   65.0
986795             2017-08-04_Seat_Leon_S_RT_Normal   2057.758  3788.0   65.0
986796             2017-08-04_Seat_Leon_S_RT_Normal   2057.847  3788.0   65.0

In [7]:
df.nlargest(
    20,
    "speed"
)[
    [
        "session_id",
        "timestamp",
        "speed",
        "rpm"
    ]
]

                                         session_id  timestamp  speed     rpm
1041002             2017-08-07_Seat_Leon_KA_RT_Frei   1720.608  218.0  3682.0
1041003             2017-08-07_Seat_Leon_KA_RT_Frei   1720.801  218.0  3682.0
1041004             2017-08-07_Seat_Leon_KA_RT_Frei   1720.937  218.0  3682.0
1041005             2017-08-07_Seat_Leon_KA_RT_Frei   1721.133  218.0  3682.0
1041006             2017-08-07_Seat_Leon_KA_RT_Frei   1721.680  218.0  3682.0
1041007             2017-08-07_Seat_Leon_KA_RT_Frei   1721.957  218.0  3682.0
1041008             2017-08-07_Seat_Leon_KA_RT_Frei   1722.368  218.0  3682.0
1041009             2017-08-07_Seat_Leon_KA_RT_Frei   1722.697  218.0  3682.0
1041010             2017-08-07_Seat_Leon_KA_RT_Frei   1723.000  218.0  3682.0
1041011             2017-08-07_Seat_Leon_KA_RT_Frei   1723.413  218.0  3564.0
441817   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.177  217.0  3658.0
441818   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.238  217.0  3658.0
441819   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.327  217.0  3658.0
441820   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.388  217.0  3658.0
441821   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.477  217.0  3658.0
441822   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.538  217.0  3658.0
441823   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.627  217.0  3658.0
441824   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.689  217.0  3658.0
441825   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.777  217.0  3658.0
441826   2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler   3334.838  217.0  3615.0

In [8]:
df.nlargest(
    20,
    "rpm_delta"
)[
    [
        "session_id",
        "timestamp",
        "rpm",
        "rpm_delta",
        "speed"
    ]
]

,session_id,timestamp,rpm,rpm_delta,speed
1378954,2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis,2696.808,2901.0,1866.0,10.0
471017,2017-07-14_Seat_Leon_KA_KA_Frei,432.091,2562.0,1609.0,78.0
1478202,2018-02-20_Seat_Leon_KA_KA_Frei,662.410,2785.0,1608.0,57.0
640888,2017-07-26_Seat_Leon_S_KA_Normal,1602.176,2457.0,1562.0,49.0
1015121,2017-08-05_Seat_Leon_S_CW_Normal,2385.718,2439.0,1531.0,46.0
2080553,2018-03-07_Seat_Leon_RT_S_Normal,1202.578,2491.0,1466.0,69.0
2607854,2018-04-23_Seat_Leon_KA_KA_Frei,79.051,2835.0,1459.0,31.0
518840,2017-07-14_Seat_Leon_KA_RT_Normal,5301.682,2733.0,1419.0,11.0
1378964,2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis,2697.709,4315.0,1414.0,26.0
646398,2017-07-26_Seat_Leon_S_KA_Normal,2870.611,2392.0,1411.0,73.0
986737,2017-08-04_Seat_Leon_S_RT_Normal,2053.259,3479.0,1402.0,19.0
287307,2017-07-11_Seat_Leon_KA_S_Normal,3175.014,2486.0,1395.0,46.0
646018,2017-07-26_Seat_Leon_S_KA_Normal,2782.310,2842.0,1395.0,29.0
434919,2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler,2750.531,2366.0,1390.0,94.0
543700,2017-07-24_Seat_Leon_RT_KA_Normal,1438.236,2297.0,1380.0,63.0
295168,2017-07-11_Seat_Leon_S_RT_Frei,323.133,2556.0,1377.0,53.0
1638009,2018-02-23_Seat_Leon_RT_S_Normal,2350.989,2257.0,1373.0,76.0
277557,2017-07-11_Seat_Leon_KA_S_Normal,2346.323,2644.0,1371.0,74.0
217604,2017-07-07_Seat_Leon_S_RT_Normal,2375.791,1367.0,1367.0,0.0
490661,2017-07-14_Seat_Leon_KA_RT_Normal,1879.414,2407.0,1357.0,72.0

In [9]:
df.nsmallest(
    20,
    "rpm_delta"
)[
    [
        "session_id",
        "timestamp",
        "rpm",
        "rpm_delta",
        "speed"
    ]
]

,session_id,timestamp,rpm,rpm_delta,speed
1378974,2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis,2698.609,1612.0,-2703.0,39.0
1015651,2017-08-05_Seat_Leon_S_CW_Normal,2453.218,1631.0,-1569.0,63.0
966287,2017-08-04_Seat_Leon_S_RT_Normal,322.351,1752.0,-1380.0,28.0
1034751,2017-08-07_Seat_Leon_KA_RT_Frei,501.051,983.0,-1328.0,62.0
1618339,2018-02-23_Seat_Leon_RT_S_Normal,682.786,1719.0,-1300.0,28.0
986757,2017-08-04_Seat_Leon_S_RT_Normal,2054.759,2165.0,-1292.0,36.0
1121454,2017-08-08_Seat_Leon_RT_S_Normal,2956.833,1130.0,-1252.0,26.0
958956,2017-08-03_Seat_Leon_S_RT_Normal,2058.099,1684.0,-1208.0,27.0
1389256,2018-02-17_Seat_Leon_RT_BB_Frei,44.516,1327.0,-1207.0,23.0
1058263,2017-08-07_Seat_Leon_RT_KA_Frei_Vollbremsung,8.851,1068.0,-1205.0,20.0
1663504,2018-02-23_Seat_Leon_S_S_Stau,74.639,1190.0,-1193.0,21.0
2347444,2018-03-22_Seat_Leon_RT_S_Normal,1846.819,1593.0,-1182.0,72.0
227331,2017-07-10_Seat_Leon_KA_KA_Stau,807.148,1098.0,-1178.0,21.0
645928,2017-07-26_Seat_Leon_S_KA_Normal,2758.302,894.0,-1172.0,60.0
1029551,2017-08-05_Seat_Leon_S_CW_Normal,4154.188,1321.0,-1170.0,23.0
2607864,2018-04-23_Seat_Leon_KA_KA_Frei,79.981,1665.0,-1170.0,30.0
520620,2017-07-14_Seat_Leon_KA_RT_Normal,5528.669,1436.0,-1160.0,24.0
1488296,2018-02-21_Seat_Leon_BB_RT_Normal,637.732,1409.0,-1154.0,104.0
2467934,2018-03-26_Seat_Leon_RT_S_Normal,64.621,1113.0,-1153.0,20.0
74083,2017-07-05_Seat_Leon_S_KA_Normal,3003.062,958.0,-1146.0,36.0

In [10]:
df.nlargest(
    20,
    "speed_delta"
)[
    [
        "session_id",
        "timestamp",
        "speed",
        "speed_delta",
        "rpm"
    ]
]

,session_id,timestamp,speed,speed_delta,rpm
1307891,2018-02-14_Seat_Leon_S_RT_Normal,1749.958,61.0,43.0,1521.0
407011,2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler,142.061,48.0,39.0,1779.0
518871,2017-07-14_Seat_Leon_KA_RT_Normal,5306.604,63.0,24.0,3096.0
646019,2017-07-26_Seat_Leon_S_KA_Normal,2782.585,51.0,22.0,2842.0
858604,2017-08-01_Seat_Leon_KA_RT_Normal,866.390,84.0,22.0,1619.0
858784,2017-08-01_Seat_Leon_KA_RT_Normal,1039.219,114.0,18.0,1898.0
71594,2017-07-05_Seat_Leon_S_KA_Normal,2432.602,43.0,17.0,2477.0
1056412,2017-08-07_Seat_Leon_KA_RT_Frei,3678.604,21.0,17.0,2316.0
73324,2017-07-05_Seat_Leon_S_KA_Normal,2836.661,16.0,16.0,1738.0
484112,2017-07-14_Seat_Leon_KA_RT_Normal,1232.047,27.0,16.0,2781.0
647259,2017-07-26_Seat_Leon_S_KA_Normal,3055.219,37.0,16.0,2140.0
1063994,2017-08-07_Seat_Leon_RT_KA_Frei_Vollbremsung,705.325,42.0,16.0,2414.0
1099145,2017-08-08_Seat_Leon_RT_S_Normal,233.915,40.0,16.0,2324.0
1099715,2017-08-08_Seat_Leon_RT_S_Normal,305.555,22.0,16.0,2472.0
1378955,2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis,2696.898,26.0,16.0,2901.0
1477463,2018-02-20_Seat_Leon_KA_KA_Frei,501.646,16.0,16.0,1787.0
1477483,2018-02-20_Seat_Leon_KA_KA_Frei,505.938,39.0,16.0,2216.0
2365688,2018-03-22_Seat_Leon_S_RT_Normal,197.705,60.0,16.0,2193.0
2366108,2018-03-22_Seat_Leon_S_RT_Normal,262.322,44.0,16.0,2505.0
72024,2017-07-05_Seat_Leon_S_KA_Normal,2521.043,22.0,15.0,2426.0